### PR TITLE
WRKLDS-806: bump k8s to 1.28

### PR DESCRIPTION
**Pull request by atiratree**
includes an override to vendor the release-1.28 branch sooner before it is released: https://github.com/openshift/cluster-policy-controller/commit/2fff150ec8306d0a3042bd124644ce6fce457845

to fix the failing builds: https://github.com/openshift/cluster-policy-controller/pull/132#issuecomment-1727966185

### CODE REVIEW

**Comment by atiratree** [comment]
/hold

build failing with 

```
 # github.com/openshift/cluster-policy-controller/pkg/quota/clusterquotareconciliation
pkg/quota/clusterquotareconciliation/reconciliation_controller.go:104:22: undefined: resourcequota.NewMonitor 
```

requires an upstream regression fix https://github.com/kubernetes/kubernetes/pull/120777

**Comment by atiratree** [comment]
added an override to vendor the release-1.28 branch sooner before it is released: https://github.com/openshift/cluster-policy-controller/pull/132/commits/2fff150ec8306d0a3042bd124644ce6fce457845

the tests should pass now

**Review by soltysh — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
