### PR TITLE
Add logs for quota namespace syncing with verbosity level 2

### PR DESCRIPTION
**Pull request by ardaguclu**
There is a flaky test failure which is tracked in https://issues.redhat.com/browse/OCPBUGS-15568 in regards to
cluster quota. Up to this point, investigations(https://github.com/openshift/origin/pull/28026, https://github.com/openshift/origin/pull/28032) proved that quota reconciliation does not update
`ClusterResourceQuotaStatus` with the matching namespaces accordingly(as seen in the [example failed job](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.14-e2e-gcp-sdn/1678163806590603264/artifacts/e2e-gcp-sdn/openshift-e2e-test/build-log.txt)) (actually it does not update `ClusterResourceQuotaStatus` at all).

This PR adds more logs to better investigate the problem. Since these logs are being added with verbosity level 2, there might not be needed to revert these logs, once investigation is completed, unless it generates noise in CI jobs.

### CODE REVIEW

**Comment by ardaguclu** [comment]
/cc @ingvagabund 
could you PTAL?. Thanks.

**Comment by ardaguclu** [comment]
@ingvagabund as we talked earlier, I have added more logs from your commit https://github.com/ingvagabund/cluster-policy-controller/commit/c6a91c6cc3190f8fdd4fb632345228c283555856

**Comment by ingvagabund** [comment]
Thx! Let's see how many new log lines the CI will produce.

**Pull request merged**
