### PR TITLE
Revert "Revert "psalabelsyncer: synchronize the enforcement label""

### PR DESCRIPTION
**Pull request by stlaz**
This reverts commit 31fc45860bfb9eacb4d97797e7c473340903593e.

/assign @ibihim

### CODE REVIEW

**Comment by stlaz** [comment]
/retest
infra

/payload 4.12 ci blocking
/payload 4.12 ci informing

the previous tests did not seem to use the fixed payload yet

**Comment by stlaz** [comment]
/payload 4.12 ci blocking
/payload 4.12 ci informing

The tests appear to pass locally on the latest 4.12 payload, I don't understand why they are failing like so. It almost looks like they did not pick up the fixed origin yet. Attempting again.

**Comment by stlaz** [comment]
/test all
/payload 4.12 ci blocking
/payload 4.12 ci informing

https://github.com/openshift/origin/pull/27347 merged with the latest fix for OVN

**Comment by stlaz** [comment]
/retest
/assign @dgoodwin 
the failures seem to be unrelated and the failures that lead to the original revert appear to be fixed

**Comment by stlaz** [comment]
/retest
infra failure

**Comment by dgoodwin** [comment]
/payload 4.12 nightly blocking

We did have blocked nightly payloads as well on gcp and azure, so this should give us confidence there. Looking really promising though.

**Comment by stlaz** [comment]
/payload 4.12 nightly blocking

All tests except for periodic-ci-openshift-release-master-ci-4.12-e2e-azure-ovn-upgrade passed, the failure in this run does not seem to be related but I am going to run the payload once more to make sure.

**Pull request merged**
