### PR TITLE
Bug 1855575: update deps to k8s 1.19 rc2

### PR DESCRIPTION
**Pull request by soltysh**
/assign @damemi 
You missed a spot :wink:

### CODE REVIEW

**Comment by damemi** [comment]
Verify-deps hitting the go minimum version check: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_cluster-policy-controller/35/pull-ci-openshift-cluster-policy-controller-master-verify-deps/1293170887234686976#1:build-log.txt%3A28

Is that referring to the go.mod version or the CI image version?

**Comment by soltysh** [comment]
/hold
for https://github.com/openshift/release/pull/10899

**Pull request merged**
